### ISSUE TITLE
Parse through an entire project to generate a README.md file

### ISSUE THREAD

**Issue by Mounayer** [peterdanwan/gimme_readme#11]
# Description

Maybe you can create a feature that parses through an entire project, reads all the files so context is there, and generates 1 README.md file for the entire project!

## Usage Example

```bash
gr-ai -f FOLDER_PATH -o README.md -m gemini-1.5-flash
```

**Comment by peterdanwan** [comment]
@Mounayer that's a really good suggestion! 

After writing some tests for my existing code, I'll work on implementing this feature!

As I work on this feature, I'll also focus on ways to avoid sending `sensitive information`, such as `.env` files or unnecessary contents within folders such as `node_modules`.

I might rely on the fact that `within the current folder that the user executes gr-ai`, there's a `.gitignore` that `gr-ai` can use, so it knows which folders and files to avoid sending.

In addition, I might add some extra key-value pair in the `.gimme_readme_config` that will be an array of folders and files to always avoid sending.

**Comment by peterdanwan** [comment]
Hi @Mounayer! Just wanted to let you know that this issue was closed by <https://github.com/peterdanwan/gimme_readme/commit/4dd7dabfd812fa2ca7a1cfa8ba1db54f4cb2b6ab>

**Comment by Mounayer** [comment]
Well done bud!

> Hi @Mounayer! Just wanted to let you know that this issue was closed by [4dd7dab](https://github.com/peterdanwan/gimme_readme/commit/4dd7dabfd812fa2ca7a1cfa8ba1db54f4cb2b6ab)

Well done bud!
