### ISSUE TITLE
Add support for --token-usage/-t for gimme_readme

### ISSUE THREAD

**Issue by Kannav02** [peterdanwan/gimme_readme#21]
This feature request proposes adding a new command-line flag (--token-usage or -t) to report token usage information to stderr.

This feature addition would achieve the following things:

1) The flag will display the number of tokens sent in the prompt and returned in the completion, leveraging the usage data provided in the LLM API response. 
2) This addition will help users better understand and manage their token consumption when interacting with the model.

 I would be eager to take on the implementation of this feature if you approve.

Thank you!

**Comment by peterdanwan** [comment]
Hi @Kannav02, this would be a _great_ feature.

Just to keep you posted, I believe I have `-t` as the shorthand for `--temperature`.

For the option flag that you add, can you use `-tkn`, which would be the shorthand of `--token`?

Thank you!

**Comment by Kannav02** [comment]
Sure! , I'll use -tkn as the shorthand 

thank you!

**Comment by peterdanwan** [comment]
Issue closed with PR #25.
