### ISSUE TITLE
Allow the user to specify an API provider

### ISSUE THREAD

**Issue by AryanK1511** [peterdanwan/gimme_readme#3]
Currently, your code defaults to using [Google Gemini API](https://ai.google.dev/gemini-api/docs) whenever a user prompts for information. As per our discussion, it would be great to have other providers such as [Open AI's chatGPT API](https://platform.openai.com/docs/overview) or [grok API](https://developers.x.ai/api/) for the user to choose from.

**Comment by peterdanwan** [comment]
The framework is in place for OpenAI to be added as one of the providers for gimme_readme. Currently, `groq's` `llama3-8b-8192` model has been added to `gimme_readme`.
