### ISSUE TITLE
Publish `gimme_readme` as a package in the `npm` registry 

### ISSUE THREAD

**Issue by AryanK1511** [peterdanwan/gimme_readme#4]
This pertains to packaging up this tool and publishing it on the [npm registry](https://www.npmjs.com) so that other users can install it via `npm install` and run it on their respective devices.

**Comment by peterdanwan** [comment]
This will be done shortly after Release 0.1, where I have a short demo of this cli tool

**Comment by peterdanwan** [comment]
`gimme_readme` has been published to the [npm registry](https://www.npmjs.com/package/gimme_readme)! You can now install this program globally via `npm i -g gimme_readme`.
